# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: converter.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x63onverter.proto\x12\tconverter"!\n\x0e\x43onvertRequest\x12\x0f\n\x07message\x18\x01 \x01(\t"!\n\x0f\x43onvertResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2O\n\tConverter\x12\x42\n\x07\x43onvert\x12\x19.converter.ConvertRequest\x1a\x1a.converter.ConvertResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "converter_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_CONVERTREQUEST"]._serialized_start = 30
    _globals["_CONVERTREQUEST"]._serialized_end = 63
    _globals["_CONVERTRESPONSE"]._serialized_start = 65
    _globals["_CONVERTRESPONSE"]._serialized_end = 98
    _globals["_CONVERTER"]._serialized_start = 100
    _globals["_CONVERTER"]._serialized_end = 179
# @@protoc_insertion_point(module_scope)
