version: '3'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8501:8501"
    depends_on:
      - grpc-server

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"